#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abot.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webgraph")]
	public partial class WebPageDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWebPage(WebPage instance);
    partial void UpdateWebPage(WebPage instance);
    partial void DeleteWebPage(WebPage instance);
    #endregion
		
		public WebPageDataContext() : 
				base(global::Abot.Properties.Settings.Default.webgraphConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WebPageDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebPageDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebPageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebPageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WebPage> WebPages
		{
			get
			{
				return this.GetTable<WebPage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebPage")]
	public partial class WebPage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pageId;
		
		private string _pageUrl;
		
		private string _parentUrl;
		
		private string _requestStartTime;
		
		private string _requestEndTime;
		
		private string _downloadStartTime;
		
		private string _downloadEndTime;
		
		private string _pageHtml;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpageIdChanging(int value);
    partial void OnpageIdChanged();
    partial void OnpageUrlChanging(string value);
    partial void OnpageUrlChanged();
    partial void OnparentUrlChanging(string value);
    partial void OnparentUrlChanged();
    partial void OnrequestStartTimeChanging(string value);
    partial void OnrequestStartTimeChanged();
    partial void OnrequestEndTimeChanging(string value);
    partial void OnrequestEndTimeChanged();
    partial void OndownloadStartTimeChanging(string value);
    partial void OndownloadStartTimeChanged();
    partial void OndownloadEndTimeChanging(string value);
    partial void OndownloadEndTimeChanged();
    partial void OnpageHtmlChanging(string value);
    partial void OnpageHtmlChanged();
    #endregion
		
		public WebPage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pageId
		{
			get
			{
				return this._pageId;
			}
			set
			{
				if ((this._pageId != value))
				{
					this.OnpageIdChanging(value);
					this.SendPropertyChanging();
					this._pageId = value;
					this.SendPropertyChanged("pageId");
					this.OnpageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string pageUrl
		{
			get
			{
				return this._pageUrl;
			}
			set
			{
				if ((this._pageUrl != value))
				{
					this.OnpageUrlChanging(value);
					this.SendPropertyChanging();
					this._pageUrl = value;
					this.SendPropertyChanged("pageUrl");
					this.OnpageUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string parentUrl
		{
			get
			{
				return this._parentUrl;
			}
			set
			{
				if ((this._parentUrl != value))
				{
					this.OnparentUrlChanging(value);
					this.SendPropertyChanging();
					this._parentUrl = value;
					this.SendPropertyChanged("parentUrl");
					this.OnparentUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestStartTime", DbType="NVarChar(50)")]
		public string requestStartTime
		{
			get
			{
				return this._requestStartTime;
			}
			set
			{
				if ((this._requestStartTime != value))
				{
					this.OnrequestStartTimeChanging(value);
					this.SendPropertyChanging();
					this._requestStartTime = value;
					this.SendPropertyChanged("requestStartTime");
					this.OnrequestStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestEndTime", DbType="NVarChar(50)")]
		public string requestEndTime
		{
			get
			{
				return this._requestEndTime;
			}
			set
			{
				if ((this._requestEndTime != value))
				{
					this.OnrequestEndTimeChanging(value);
					this.SendPropertyChanging();
					this._requestEndTime = value;
					this.SendPropertyChanged("requestEndTime");
					this.OnrequestEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloadStartTime", DbType="NVarChar(50)")]
		public string downloadStartTime
		{
			get
			{
				return this._downloadStartTime;
			}
			set
			{
				if ((this._downloadStartTime != value))
				{
					this.OndownloadStartTimeChanging(value);
					this.SendPropertyChanging();
					this._downloadStartTime = value;
					this.SendPropertyChanged("downloadStartTime");
					this.OndownloadStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloadEndTime", DbType="NVarChar(50)")]
		public string downloadEndTime
		{
			get
			{
				return this._downloadEndTime;
			}
			set
			{
				if ((this._downloadEndTime != value))
				{
					this.OndownloadEndTimeChanging(value);
					this.SendPropertyChanging();
					this._downloadEndTime = value;
					this.SendPropertyChanged("downloadEndTime");
					this.OndownloadEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageHtml", DbType="NVarChar(MAX)")]
		public string pageHtml
		{
			get
			{
				return this._pageHtml;
			}
			set
			{
				if ((this._pageHtml != value))
				{
					this.OnpageHtmlChanging(value);
					this.SendPropertyChanging();
					this._pageHtml = value;
					this.SendPropertyChanged("pageHtml");
					this.OnpageHtmlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
