<?xml version="1.0" encoding="utf-8"?><Database Name="webgraph" Class="WebPageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database\webgraph.mdf;Integrated Security=True" SettingsObjectName="Abot.Properties.Settings" SettingsPropertyName="webgraphConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WebPage" Member="WebPages">
    <Type Name="WebPage">
      <Column Name="pageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pageUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="parentUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="pageHtml" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>